trigger:
- main

pool:
  name: Pool_1

steps:
- script: df -h
  displayName: 'Check Disk Space'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'